### ISSUE TITLE
显示空视图的时候，原来UITableView的head和footer会被盖在下面

### ISSUE THREAD

**Issue by qingweiSun** [linhay/EmptyPage#11]

**Comment by linhay** [comment]
期望是header和footer在空视图之上, 还是不显示空视图?

**Comment by qingweiSun** [comment]
是不现实head和footer，可参考LYEmptyView 目前我改成这个了，或者在head和footer之间更好

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: linhey ***@***.***>
发送时间: Sunday, July 11, 2021 12:45:26 PM
收件人: linhay/EmptyPage ***@***.***>
抄送: 别叫我天真 ***@***.***>; Author ***@***.***>
主题: Re: [linhay/EmptyPage] 显示空视图的时候，原来UITableView的head和footer会被盖在下面 (#11)


期望是header和footer在空视图之上, 还是不显示空视图?

―

**Comment by linhay** [comment]
我在  **[4.0.7](https://github.com/linhay/EmptyPage/releases/tag/4.0.7)** 中修改了对应的逻辑.
在TableView & CollectionView, 存在 header & footer 则不会显示空页面.
感谢你的反馈~🙏🏻🙏🏻🙏🏻
