### ISSUE TITLE
小建议：增加多一个能全局设置的所有scrollview，tableview，collectionview的无数据页面的参数

### ISSUE THREAD

**Issue by cs571393** [linhay/EmptyPage#4]

**Comment by linhay** [comment]
能具体描述下场景嘛?是全局共用一套模板?

**Comment by cs571393** [comment]
因为毕竟用到tableview的列表场景比较多。如果能设置一个默认的全局无数据页面，那就不用一个个去设置了。就只要在不用无数据页面的tableview去除就好。写起来就方便一点。

**Comment by linhay** [comment]
正在添加相应API,稍等一会

**Comment by linhay** [comment]
@cs571393 相应功能添加到[[3.3.0](https://github.com/linhay/EmptyPage/releases/tag/3.3.0)]了
