### ISSUE TITLE
配合mj使用的时候界面会跳动

### ISSUE THREAD

**Issue by huyabin** [linhay/EmptyPage#5]
使用文字或图片或者标准图片的时候这个时候tableview还是可以拉动的，拉动之后界面一直跳啊跳。能否有设置可以在没数据的时候关闭tableview的拉动的属性。

**Comment by linhay** [comment]
好的, 我看一下

**Comment by linhay** [comment]
> 使用文字或图片或者标准图片的时候这个时候tableview还是可以拉动的，拉动之后界面一直跳啊跳。能否有设置可以在没数据的时候关闭tableview的拉动的属性。

在3.3.1版本里禁用拉动属性
