### ISSUE TITLE
设置了空白页 ，好像就不能使用下拉刷新了，有解决方法吗

### ISSUE THREAD

**Issue by Mase9527** [linhay/EmptyPage#6]

**Comment by linhay** [comment]
### 是的, 目前 4.0.0[未发布] 中添加了空白页是否可以滚动的支持,

```swift
 scrollView.ep.isScrollEnabled = true  // 当空白页显示时可以滚动
 scrollView.ep.isScrollEnabled = false // 当空白页显示时不可以滚动
```

你可以提前试用4.0.0的版本: 

```ruby
pod 'EmptyPage', :git => 'git@github.com:linhay/EmptyPage.git', :branch => '4.0.0-dev'
```

### 在 3.x 的版本用以下方式启用:

```swift
tableView.reloadData()
tableView.isScrollEnabled = true
```

### 但是我更推荐将加载页面事件绑定于空白页的按钮上.

**Comment by Mase9527** [comment]
> ### 是的, 目前 4.0.0[未发布] 中添加了空白页是否可以滚动的支持,
> ```swift
>  scrollView.ep.isScrollEnabled = true  // 当空白页显示时可以滚动
>  scrollView.ep.isScrollEnabled = false // 当空白页显示时不可以滚动
> ```
> 
> 你可以提前试用4.0.0的版本:
> 
> ```ruby
> pod 'EmptyPage', :git => 'git@github.com:linhay/EmptyPage.git', :branch => '4.0.0-dev'
> ```
> 
> ### 在 3.x 的版本用以下方式启用:
> ```swift
> tableView.reloadData()
> tableView.isScrollEnabled = true
> ```
> 
> ### 但是我更推荐将加载页面事件绑定于空白页的按钮上.

好的 谢谢 我先试用下4.0 的看看效果咋样

**Comment by Mase9527** [comment]
> > ### 是的, 目前 4.0.0[未发布] 中添加了空白页是否可以滚动的支持,
> > ```swift
> >  scrollView.ep.isScrollEnabled = true  // 当空白页显示时可以滚动
> >  scrollView.ep.isScrollEnabled = false // 当空白页显示时不可以滚动
> > ```
> > 
> > 
> > 你可以提前试用4.0.0的版本:
> > ```ruby
> > pod 'EmptyPage', :git => 'git@github.com:linhay/EmptyPage.git', :branch => '4.0.0-dev'
> > ```
> > 
> > 
> > ### 在 3.x 的版本用以下方式启用:
> > ```swift
> > tableView.reloadData()
> > tableView.isScrollEnabled = true
> > ```
> > 
> > 
> > ### 但是我更推荐将加载页面事件绑定于空白页的按钮上.
> 
> 好的 谢谢 我先试用下4.0 的看看效果咋样

[!] Error installing EmptyPage
[!] Failed to download 'EmptyPage': [!] /usr/bin/git clone git@github.com:linhay/EmptyPage.git /var/folders/l2/m9pb0q753rl54df7c2hzr3cm0000gn/T/d20200608-9177-jkavc --template= --single-branch --depth 1 --branch 4.0.0-dev

Cloning into '/var/folders/l2/m9pb0q753rl54df7c2hzr3cm0000gn/T/d20200608-9177-jkavc'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.



提示我没有权限  Permission denied (publickey).

**Comment by linhay** [comment]
这样写..., 不能用ssh
```ruby
pod 'EmptyPage', :git => 'https://github.com/linhay/EmptyPage.git', :branch => '4.0.0-dev'
```
