### ISSUE TITLE
setEmptyView 3.3.1版本有问题

### ISSUE THREAD

**Issue by robin2005** [linhay/EmptyPage#8]
func setEmptyView(_ isEmpty: Bool) {
        guard isEmpty else {
            **_isScrollEnabled = oldIsScrollEnabled_**
            firstLoadingView?.removeFromSuperview()
            emptyView?.removeFromSuperview()
            oldEmptyView?.removeFromSuperview()
            return
        }

        if oldEmptyView?.superview !== self {
            oldIsScrollEnabled = isScrollEnabled
            isScrollEnabled = isEmpty == false
        }

        oldEmptyView?.removeFromSuperview()
--------------------------------------------------
oldIsScrollEnabled 我用RxDataSources 实现数据绑定的话，有数据他是禁止滑动的。
跟断点发现的

**Comment by xmw-simon** [comment]
我也发现有这个问题，版主能解决一下么

**Comment by linhay** [comment]
@robin2005 @xmw1992 
我在 4.0.0 中重构了这部分逻辑, 现在还在补文档中.
不介意的话可以先用下面的方式试用下, 看下问题是否还存在😁
```ruby
pod 'EmptyPage', :git => 'https://github.com/linhay/EmptyPage'
```

**Comment by xmw-simon** [comment]
ok 非常感谢
