### ISSUE TITLE
关于3.3.1 更新的反馈

### ISSUE THREAD

**Issue by ios-zl** [linhay/EmptyPage#9]
3.3.1 fix: 显示空白页时禁止ScrollView滑动。
兄弟我集成了你的Widget,在基类进行封装,更新以后发现偶然情况无法滑动列表... 以前用的好好地突然不能用,找了好久没发现是你这边的问题... 得亏测出来了没上线,不然惨了。 个人觉着你的2.0版本就挺够用了,弄个全局也没啥意思吧,囧。

**Comment by linhay** [comment]
3.3.1 在设计和逻辑上的确存在比较多的问题, 万分抱歉😢😢😢
4.0.x 我重新梳理代码, 移除了不合理的逻辑, 现在已经在线上跑了几个月, 欢迎试用~
